name: build

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: cmake configuration
        run: cmake -DCMAKE_BUILD_TYPE=Debug -Bbuild

      - name: cmake build
        run: cmake --build build -j $(nproc)
